/* Auto-generated from lexicon.docx (11 tables, 81 entries). */
window.SADAQAH_LEXICON = [
  { arabic: "ﺻَدَﻗَﺔ", translit: "ṣadaqah", en_use: "Charity in the general sense; any voluntary gift given for the sake of God.", ar_use: "الصدقة بمعناها العام؛ أي هبة طوعية تُقدم في سبيل الله." },
  { arabic: "زَﻛَﺎة", translit: "zakāh", en_use: "Obligatory alms; the fourth pillar of Islam; a ﬁxed percentage of qualifying wealth.", ar_use: "الزكاة المفروضة؛ الركن الرابع من أركان الإسلام؛ نسبة ثابتة من الثروة المؤهلة." },
  { arabic: "زَﻛَﺎة اﻟﻔِطْر", translit: "zakāt al-ﬁṭr", en_use: "The alms of fast-breaking, given at the end of Ramadan.", ar_use: "صدقة الإفطار، التي تُقدم في نهاية شهر رمضان." },
  { arabic: "ﺻَدَﻗَﺔ ﺟَﺎرِﯾَﺔ", translit: "ṣadaqah jāriyah", en_use: "Ongoing charity whose beneﬁt continues after the giver's death (wells, mosques, schools).", ar_use: "الأعمال الخيرية المستمرة التي يستمر نفعها بعد وفاة المتبرع (الآبار، المساجد، المدارس)." },
  { arabic: "وَﻗْف / أَوْﻗَﺎف", translit: "waqf / awqāf", en_use: "Religious endowment; the dedication of an asset whose usufruct is perpetually devoted to charity.", ar_use: "الوقف الديني؛ تخصيص أصل يُكرس منفعته بشكل دائم للأعمال الخيرية." },
  { arabic: "إِﻧْﻔَﺎق", translit: "infāq", en_use: "Spending (in the path of God); a broader Qur'anic category including ṣadaqah.", ar_use: "الإنفاق (في سبيل الله)؛ فئة قرآنية أوسع تشمل صدقة." },
  { arabic: "إِﯾﺗَﺎء", translit: "īʾtāʾ", en_use: "Giving, paying (e.g., īʾtāʾ al-zakāh).", ar_use: "العطاء، الدفع (على سبيل المثال الإيتاء ، الزكاة)" },
  { arabic: "إﺣْﺳَﺎن", translit: "iḥsān", en_use: "Excellence; doing good; a near-synonym of charity in its broadest sense.", ar_use: "التميز؛ فعل الخير؛ مرادف شبه كامل للعمل الخيري بمعناه الأوسع." },
  { arabic: "ﺑِرّ", translit: "birr", en_use: "Righteousness, dutiful goodness (esp. toward parents and kin).", ar_use: "البر، والصلاح الواجب (وخاصة تجاه الوالدين والأقارب)." },
  { arabic: "ﺗَﺑَرُّع", translit: "tabarruʿ", en_use: "Voluntary donation; used for donations to NGOs and causes.", ar_use: "التبرع الطوعي؛ يستخدم للتبرعات للمنظمات غير الحكومية والقضايا الإنسانية." },
  { arabic: "ھِﺑَﺔ", translit: "hibah", en_use: "Gift; a legal category of transfer without compensation.", ar_use: "فئة قانونية من التحويلات بدون مقابل." },
  { arabic: "عَطِيَّة", translit: "ʿaṭiyyah", en_use: "Gift, gratuity.", ar_use: "هدية، إكرامية." },
  { arabic: "ﻣَﻌْرُوف", translit: "maʿrūf", en_use: "That which is recognised as good; a small kindness counted as charity.", ar_use: "ما يُعتبر خيراً؛ فالإحسان الصغير يُعدّ صدقة." },
  { arabic: "إِطْﻌَﺎم", translit: "iṭʿām", en_use: "Feeding (the hungry); a speciﬁc Qur'anic category of charity.", ar_use: "إطعام (الجياع)؛ فئة محددة من الصدقة في القرآن الكريم." },
  { arabic: "كَفَّارّة", translit: "kaﬀārah", en_use: "Expiation; obligatory charitable payment to atone for certain sins.", ar_use: "دفع صدقة واجبة للتكفير عن ذنوب معينة." },
  { arabic: "ﻓِدْﯾَﺔ", translit: "ﬁdyah", en_use: "Ransom / compensatory payment (e.g., for missed fasts).", ar_use: "الفدية / الدفعة التعويضية (على سبيل المثال، عن الصيام الفائت)." },
  { arabic: "ﻧَﻔَﻘَﺔ", translit: "nafaqah", en_use: "Maintenance; obligatory spending on dependents.", ar_use: "النفقة؛ الإنفاق الإلزامي على المعالين." },
  { arabic: "إِﯾﺛَﺎر", translit: "īthār", en_use: "Preferring others over oneself; the highest form of giving.", ar_use: "تفضيل الآخرين على النفس؛ أسمى أشكال العطاء." },
  { arabic: "ﺳَﺧَﺎء / ﻛَرَم", translit: "sakhāʾ / karam", en_use: "Generosity; classical virtues intimately tied to charity.", ar_use: "الكرم؛ فضائل كلاسيكية مرتبطة ارتباطاً وثيقاً بالصدقة." },
  { arabic: "ﺟُود", translit: "jūd", en_use: "Abundant generosity; the giving of what is not strictly required.", ar_use: "كرمٌ وفير؛ إعطاء ما ليس مطلوباً بالضرورة." },
  { arabic: "جَمْعِيَّة خَيْرِيَّة", translit: "jamʿiyyah khayriyyah", en_use: "Charitable society / NGO.", ar_use: "جمعية خيرية / منظمة غير حكومية." },
  { arabic: "مُؤَسَّسَة خَيْرِيَّة", translit: "muʾassasah khayriyyah", en_use: "Charitable foundation (often waqf-based).", ar_use: "مؤسسة خيرية (غالباً ما تكون قائمة على الوقف)." },
  { arabic: "ﻋَﻣَل ﺧَﯾْرِيّ", translit: "ʿamal khayrī", en_use: "Charitable work / philanthropy.", ar_use: "العمل الخيري / العمل الخيري." },
  { arabic: "إِﻏَﺎﺛَﺔ", translit: "ighāthah", en_use: "Emergency relief aid.", ar_use: "مساعدات الإغاثة الطارئة." },
  { arabic: "ﻣُﺳَﺎﻋَدَات إِﻧْﺳَانِيَّة", translit: "musāʿadāt insāniyyah", en_use: "Humanitarian assistance.", ar_use: "المساعدة الإنسانية." },
  { arabic: "تَبَرُّعَات", translit: "tabarruʿāt", en_use: "Donations (plural).", ar_use: "التبرعات (بصيغة الجمع)." },
  { arabic: "ﺣَﻣْﻠَﺔ تَبَرُّعَات", translit: "ḥamlat tabarruʿāt", en_use: "Donation campaign.", ar_use: "حملة تبرعات." },
  { arabic: "ﻛَﻔَﺎﻟَﺔ ﯾَﺗِﯾم", translit: "kafālat yatīm", en_use: "Orphan sponsorship.", ar_use: "كفالة الأيتام." },
  { arabic: "ﺣَﻔْر اﻵﺑَﺎر", translit: "ḥafr al-ābār", en_use: "Well-drilling (a major category of ṣadaqah jāriyah).", ar_use: "حفر الآبار (فئة رئيسية من صدقة جارية)." },
  { arabic: "إِﻓْطَﺎر ﺻَﺎﺋِم", translit: "ifṭār ṣāʾim", en_use: "Providing iftar meals for fasting persons.", ar_use: "توفير وجبات الإفطار للصائمين." },
  { arabic: "ﻛِﺳْوَة اﻟشِّتَاء", translit: "kiswat al-shitāʾ", en_use: "Winter clothing drive.", ar_use: "حملة لجمع الملابس الشتوية." },
  { arabic: "ﻣَﺷْرُوع ﺧَﯾْرِيّ", translit: "mashrūʿ khayrī", en_use: "Charitable project.", ar_use: "مشروع خيري." },
  { arabic: "رِﻋَﺎﯾَﺔ", translit: "riʿāyah", en_use: "Sponsorship / patronage.", ar_use: "الرعاية / الدعم." },
  { arabic: "ﻣُﺗَﺑَرِّع", translit: "mutabarriʿ", en_use: "Donor (masc.); fem. mutabarriʿah.", ar_use: "مانح (مذكر)؛ مؤنّثها ﻣُﺗَﺑَرِّعَة" },
  { arabic: "ﻣُﺳْﺗَﻔِﯾد", translit: "mustafīd", en_use: "Beneﬁciary.", ar_use: "المستفيد." },
  { arabic: "ﻣُﺣْﺗَﺎج / ﻓَﻘِﯾر", translit: "muḥtāj / faqīr", en_use: "Person in need / poor person.", ar_use: "شخص محتاج / شخص فقير." },
  { arabic: "ﻣِﺳْﻛِﯾن", translit: "miskīn", en_use: "Destitute person (a distinct ﬁqh category).", ar_use: "الشخص المعوز (فئة فقهية مميزة)." },
  { arabic: "أَﯾْﺗَﺎم", translit: "aytām", en_use: "Orphans (plural of yatīm).", ar_use: "الأيتام (جمع كلمة يتيم)." },
  { arabic: "أَرَاﻣِل", translit: "arāmil", en_use: "Widows.", ar_use: "الأرامل." },
  { arabic: "ذَوُو اﻻﺣْﺗِﯾَﺎﺟَﺎت اﻟﺧَﺎصَّة", translit: "dhawūal-iḥtiyājāt al-khāṣṣah", en_use: "Persons with special needs / disabilities.", ar_use: "الأشخاص ذوو الاحتياجات الخاصة / الإعاقات." },
  { arabic: "ﺻُﻧْدُوق الزَّكَاة", translit: "ṣundūq al-zakāh", en_use: "Zakat fund / zakat authority.", ar_use: "صندوق الزكاة / هيئة الزكاة." },
  { arabic: "اﻟﮭَﯾْﺋَﺔ اﻟﺧَﯾْرِيَّة", translit: "al-hayʾahal-khayriyya h", en_use: "Charitable authority / body.", ar_use: "هيئة/مؤسسة خيرية." },
  { arabic: "ﻓَزْﻋَﺔ", translit: "fazʿah", en_use: "A rallying response; people rushing collectively to help someone in need. One of the most distinctive Gulf concepts of mutual aid.", ar_use: "استجابة جماعية؛ هرع الناس بشكل جماعي لمساعدة شخص محتاج. أحد أبرز مفاهيم التكافل الاجتماعي في منطقة الخليج." },
  { arabic: "ﻋَوْﻧَﺔ / ﻋُوﻧَﺔ", translit: "ʿawnah /ʿūnah", en_use: "Collective help; neighbours or kin gathering to assist (e.g., with a house, a wedding, a debt).", ar_use: "المساعدة الجماعية؛ تجمع الجيران أو الأقارب للمساعدة (على سبيل المثال، في منزل أو حفل زفاف أو دين)." },
  { arabic: "ﻛَرَم", translit: "karam", en_use: "Generosity; the deﬁning tribal and Islamic virtue of the Gulf host.", ar_use: "الكرم؛ الفضيلة القبلية والإسلامية المميزة لمضيف الخليج." },
  { arabic: "ﻧَﺧْوَة", translit: "nakhwah", en_use: "Chivalrous protective generosity; the impulse to defend and provide for kin.", ar_use: "الكرم الشهمي الحامي؛ الدافع للدفاع عن الأقارب وتوفير احتياجاتهم." },
  { arabic: "ﻣُرُوَّة", translit: "muruwwah", en_use: "Manly virtue; encompasses generosity, hospitality, and care for the weak.", ar_use: "الفضيلة الرجولية؛ تشمل الكرم، وكرم الضيافة، والاهتمام بالضعفاء." },
  { arabic: "ﯾَد ﺑَﯾْﺿَﺎ", translit: "yad bayḍā", en_use: "'A white hand' — a favour / generous act, often used with ʿind ('to have a favour upon').", ar_use: "\"يد بيضاء\" - معروف / عمل كريم، أن يكون له معروف" },
  { arabic: "ﺟُود", translit: "jūd", en_use: "Lavish generosity; praised in Nabaṭī poetry.", ar_use: "كرمٌ حاتمي، مُدِح في الشِّعر النبطي" },
  { arabic: "ﺧَﯾْر", translit: "khēr", en_use: "Good; 'ahl al-khēr' = charitable people.", ar_use: "جيد؛ أهل الخير = الناس الخيرون." },
  { arabic: "أَھْل اﻟﺧَﯾْر", translit: "ahl al-khēr", en_use: "'People of good' — a standard Gulf expression for generous donors and philanthropists.", ar_use: "تعبير خليجي شائع لوصف المتبرعين والفاعلين الخيرين الكرماء." },
  { arabic: "محَسِّن / مْحَسِّنِين", translit: "mḥassin / mḥassinīn", en_use: "Benefactor(s); used on donation boxes and charity signage across Qatar.", ar_use: "المتبرع(ون)؛ يستخدم على صناديق التبرعات ولافتات الجمعيات الخيرية في جميع أنحاء قطر." },
  { arabic: "ﺻَدْﻗَﺔ", translit: "ṣadgah /ṣadqa", en_use: "Colloquial pronunciation of ṣadaqah; used in everyday speech.", ar_use: "النطق العامي للصدقة؛ يستخدم في الكلام اليومي." },
  { arabic: "زْﻛَﺎة", translit: "zkāh", en_use: "Dialect pronunciation of zakāh.", ar_use: "نطق كلمة زَكاة باللهجة المحلية." },
  { arabic: "دِﯾرَة", translit: "dīrah", en_use: "Homeland / community; invoked in appeals to help 'ahl al-dīrah'.", ar_use: "الوطن / المجتمع؛ يتم الاستشهاد به في النداءات لمساعدة أهل الدير." },
  { arabic: "ﻋَزْوَة", translit: "ʿazwah", en_use: "Extended kin support network; the people one can rely on.", ar_use: "شبكة دعم الأقارب الممتدة؛ الأشخاص الذين يمكن الاعتماد عليهم." },
  { arabic: "ﻓَﻘِﯾر / ﻣِﺳْﻛِﯾن", translit: "fagīr / miskīn", en_use: "Poor / needy (same as MSA but with qāf > [g]).", ar_use: "فقير / محتاج" },
  { arabic: "ﻣْﺣﺗَﺎج", translit: "mḥtāj", en_use: "A person in need.", ar_use: "شخص محتاج" },
  { arabic: "ﯾْﺗِﯾم / ﯾْﺗَﺎﻣَﻰ", translit: "ytīm / ytāmā", en_use: "Orphan / orphans.", ar_use: "ﯾْﺗِﯾم / ﯾْﺗَﺎﻣَﻰ" },
  { arabic: "ﻣَﺳَﺎﻛِﯾن", translit: "masākīn", en_use: "The destitute; also used aﬀectively for 'the poor dears'.", ar_use: "المعدمون؛ ويستخدم أيضًا بشكل عاطفي للإشارة إلى \"المساكين الأعزاء\"." },
  { arabic: "وَاﺟِب", translit: "wājib", en_use: "A duty; in Gulf usage, 'hādhā wājib' ('this is a duty') is a standard response when thanked for a generous act.", ar_use: "واجب؛ في استخدام الخليج، فإن عبارة \"هذا واجب\" هي رد قياسي عند شكر شخص ما على عمل كريم." },
  { arabic: "ﻻ ﺷُﻛْر ﻋَﻠﻰ واﺟِب", translit: "lā shukr ʿalā wājib", en_use: "'No thanks are due for a duty'— the classical polite rejection of thanks for charity.", ar_use: "الرفض المهذب التقليدي للشكر على الأعمال الخيرية." },
  { arabic: "ﷲ ﯾِﻌْطِﯾك اﻟﻌَﺎﻓْﯾَﺔ", translit: "Allāh yiʿṭīk al-ʿāfyah", en_use: "'May God give youwell-being' — said to thank a worker, donor, or helper.", ar_use: "تُقال لشكر عامل أو متبرع أو مساعد." },
  { arabic: "ﷲ ﯾْﺑَﺎرِك ﻓِﯾك", translit: "Allāh ybārik fīk", en_use: "'May God bless you' — common response to a generous act.", ar_use: "رد شائع على عمل كريم." },
  { arabic: "ﺟَزَاك ﷲ ﺧَﯾْر", translit: "jazāk Allāh khēr", en_use: "'May God reward you with good' — the standard Islamic thanks to a donor.", ar_use: "هي عبارة الشكر الإسلامية المعتادة للمتبرع." },
  { arabic: "ﷲ ﯾَرْﺣَم واﻟدِﯾك", translit: "Allāh yirḥam wāldīk", en_use: "'May God have mercy on your parents' — said to a helper, often linked to ṣadaqah on behalf of the dead.", ar_use: "تُقال هذه العبارة للمساعد، وغالبًا ما ترتبط بـصدقة نيابة عن الموتى" },
  { arabic: "ﻓﻲ ﺳَﺑِﯾل ﷲ", translit: "fī sabīl Allāh", en_use: "'In the path of God' — the theological frame for any act of ṣadaqah.", ar_use: "الإطار اللاهوتي لأي عمل من أعمال الصدقة." },
  { arabic: "ﻟِوَﺟْﮫ ﷲ", translit: "li-wajh Allāh", en_use: "'For the face of God' — for God's sake alone; a disclaimer of worldly return.", ar_use: "من أجل الله وحده؛ تنصل من العودة الدنيوية" },
  { arabic: "ﺻَدَﻗَﺔ ﻟِرُوح ﻓْﻼن", translit: "ṣadagah li-rūḥ ﬂān", en_use: "'A charity for the soul ofso-and-so' — charity given on behalf of a deceased relative.", ar_use: "صدقة تُقدم نيابة عن قريب متوفى." },
  { arabic: "إِﻓْطَﺎر ﺻَﺎﯾِم", translit: "ifṭār ṣāyim", en_use: "Dialect form of 'providing iftar for the fasting' — a major Ramadan campaign category in Qatar.", ar_use: "صيغة عاميّة لعبارة \"توفير الإفطار للصائمين\" - وهي فئة رئيسية من حملات رمضان في قطر." },
  { arabic: "ﻛَﻔَﺎﻟَﺔ ﯾْﺗِﯾم", translit: "kafālat ytīm", en_use: "Orphan sponsorship; the term dominates Qatari charity appeals.", ar_use: "هذا المصطلح يهيمن على حملات التبرعات الخيرية القطرية." },
  { arabic: "ﻗَطَر اﻟﺧَﯾْرِيَّة", translit: "Qaṭaral-khayriyya h", en_use: "Qatar Charity — the country's largest charitable NGO.", ar_use: "أكبر منظمة غير حكومية خيرية في البلاد" },
  { arabic: "اﻟﮭِﻼَل اﻷَﺣْﻣَر اﻟﻘَطَرِي", translit: "al-hilālal-aḥmar al-qaṭarī", en_use: "Qatar Red Crescent Society.", ar_use: "جمعية الهلال الأحمر القطري." },
  { arabic: "مُؤَسَّسَة الشَّيْخ عِيد الخَيْرِيَّة", translit: "muʾassasat al-shaykh ʿĪdal-khayriyya h", en_use: "Eid Charity Foundation (a major Qatari waqf foundation).", ar_use: "مؤسسة وقف قطرية رئيسية" },
  { arabic: "ﻣؤََسَّسَة راف", translit: "muʾassasat RAF", en_use: "RAF Foundation (Qatari humanitarian foundation).", ar_use: "مؤسسة القوات الجوية الملكية (مؤسسة قطرية إنسانية)." },
  { arabic: "ﺻُﻧْدُوق اﻟزَّكَاة", translit: "ṣundūq al-zakāh", en_use: "Zakat Fund (the Qatari state zakat authority operating under the Ministry of Awqaf).", ar_use: "هيئة الزكاة الحكومية القطرية العاملة تحت إشراف وزارة الأوقاف." },
  { arabic: "وَزَارَة اﻷَوْﻗَﺎف واﻟشؤُون الإسْلامِيَّة", translit: "wizāratal-awqāf wa al-shuʾūnal-islāmiyya h", en_use: "Ministry of Awqaf and Islamic Aﬀairs — the ministry supervising religious endowments and charitable regulation in Qatar.", ar_use: "الوزارة التي تشرف على الأوقاف الدينية والتنظيم الخيري في قطر." },
  { arabic: "تْبَرَّع اﻟﺣِﯾن", translit: "tbarraʿ al-ḥīn", en_use: "'Donate now' — a ubiquitous slogan on Qatari charity posters and SMS fundraising.", ar_use: "\"شعار منتشر في كل مكان على ملصقات الجمعيات الخيرية القطرية ورسائل التبرع عبر الرسائل النصية القصيرة." },
  { arabic: "ﺷﺎرِك ﻓﻲ اﻟﺧَﯾْر", translit: "shārik fī al-khēr", en_use: "'Take part in the good' — typical Gulf campaign framing.", ar_use: "إطار نموذجي لحملات الخليج." },
  { arabic: "ﺣَقّ ﷲ", translit: "ḥagg Allāh", en_use: "'God's right' — a dialectal way of describing obligatory zakāh as a right owed to God.", ar_use: "طريقة عامية لوصف الزكاة الواجبة كحق مستحق لله." },
  { arabic: "رَدّ اﻟﺟَﻣِﯾل", translit: "radd al-jamīl", en_use: "'Returning the favour' — commonly invoked in appeals to support one's community.", ar_use: "هو مصطلح شائع الاستخدام في النداءات لدعم المجتمع." }
];
